#!/bin/bash
# ============================================================================
# Setup Authentication for Docker Deployment
# ============================================================================
#
# This script helps configure authentication for Docker deployment of
# auto-agent-harness. It supports three modes:
#
#   1. API Key Mode:   Use ANTHROPIC_API_KEY (pay-per-use)
#   2. OAuth Mode:     Mount ~/.claude/ from host (use subscription)
#   3. Extract Mode:   Extract credentials for remote server
#
# Usage:
#   ./scripts/setup-docker-auth.sh --api-key
#   ./scripts/setup-docker-auth.sh --oauth-mount
#   ./scripts/setup-docker-auth.sh --oauth-extract
#   ./scripts/setup-docker-auth.sh --interactive
#
# ============================================================================

set -e

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Print header
print_header() {
    echo -e "${CYAN}"
    echo "=============================================="
    echo "  Auto-Agent-Harness Docker Auth Setup"
    echo "=============================================="
    echo -e "${NC}"
}

# Print mode info
print_mode_info() {
    echo -e "${YELLOW}Available Authentication Modes:${NC}"
    echo ""
    echo "  1. API Key Mode (--api-key)"
    echo "     - Uses ANTHROPIC_API_KEY environment variable"
    echo "     - Pay-per-token pricing"
    echo "     - Best for: Servers without Claude subscription"
    echo ""
    echo "  2. OAuth Mount Mode (--oauth-mount)"
    echo "     - Mounts ~/.claude/ from host into container"
    echo "     - Uses Claude Pro/Max subscription"
    echo "     - Best for: Local Docker development"
    echo ""
    echo "  3. OAuth Extract Mode (--oauth-extract)"
    echo "     - Extracts credentials for transfer to remote server"
    echo "     - Uses Claude Pro/Max subscription"
    echo "     - Best for: Remote server deployment"
    echo ""
}

# Setup API Key mode
setup_api_key() {
    echo -e "${GREEN}Setting up API Key mode...${NC}"
    echo ""

    # Check if .env exists
    if [ -f "$PROJECT_DIR/.env" ]; then
        echo -e "${YELLOW}Found existing .env file${NC}"
    fi

    # Check if API key is set
    if [ -n "$ANTHROPIC_API_KEY" ]; then
        echo -e "${GREEN}ANTHROPIC_API_KEY is already set in environment${NC}"
    else
        echo -e "${YELLOW}Enter your Anthropic API key:${NC}"
        read -s API_KEY
        echo ""

        if [ -z "$API_KEY" ]; then
            echo -e "${RED}Error: API key cannot be empty${NC}"
            exit 1
        fi

        # Add to .env file
        if grep -q "ANTHROPIC_API_KEY" "$PROJECT_DIR/.env" 2>/dev/null; then
            # Update existing
            sed -i.bak "s|^ANTHROPIC_API_KEY=.*|ANTHROPIC_API_KEY=$API_KEY|" "$PROJECT_DIR/.env"
        else
            # Add new
            echo "ANTHROPIC_API_KEY=$API_KEY" >> "$PROJECT_DIR/.env"
        fi

        echo -e "${GREEN}API key added to .env file${NC}"
    fi

    # Generate JWT secret if not set
    if ! grep -q "JWT_SECRET_KEY" "$PROJECT_DIR/.env" 2>/dev/null; then
        JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
        echo "JWT_SECRET_KEY=$JWT_SECRET" >> "$PROJECT_DIR/.env"
        echo -e "${GREEN}Generated JWT_SECRET_KEY${NC}"
    fi

    echo ""
    echo -e "${GREEN}API Key mode setup complete!${NC}"
    echo ""
    echo "To start the container:"
    echo "  docker-compose up -d"
}

# Setup OAuth mount mode
setup_oauth_mount() {
    echo -e "${GREEN}Setting up OAuth Mount mode...${NC}"
    echo ""

    # Check if credentials exist
    CREDS_FILE="$HOME/.claude/.credentials.json"
    if [ ! -f "$CREDS_FILE" ]; then
        echo -e "${YELLOW}No Claude credentials found.${NC}"
        echo -e "${YELLOW}Running 'claude login'...${NC}"
        echo ""

        if ! command -v claude &> /dev/null; then
            echo -e "${RED}Error: Claude CLI not installed.${NC}"
            echo "Install with: npm install -g @anthropic-ai/claude-code"
            exit 1
        fi

        claude login

        if [ ! -f "$CREDS_FILE" ]; then
            echo -e "${RED}Error: Login failed or cancelled.${NC}"
            exit 1
        fi
    fi

    echo -e "${GREEN}Claude credentials found at: $CREDS_FILE${NC}"

    # Create docker-compose override for OAuth
    cat > "$PROJECT_DIR/docker-compose.override.yml" << 'EOF'
# OAuth mount mode - uses host's Claude credentials
# Generated by setup-docker-auth.sh

services:
  auto-agent-harness:
    volumes:
      - autocoder-data:/app/data
      - ${WORKSPACE_DIR:-./workspace}:/workspace
      # Mount Claude credentials from host
      - ${HOME}/.claude:/home/autocoder/.claude:ro
EOF

    echo -e "${GREEN}Created docker-compose.override.yml with OAuth mount${NC}"

    # Generate JWT secret if not set
    if [ ! -f "$PROJECT_DIR/.env" ] || ! grep -q "JWT_SECRET_KEY" "$PROJECT_DIR/.env" 2>/dev/null; then
        JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
        echo "JWT_SECRET_KEY=$JWT_SECRET" >> "$PROJECT_DIR/.env"
        echo -e "${GREEN}Generated JWT_SECRET_KEY${NC}"
    fi

    echo ""
    echo -e "${GREEN}OAuth Mount mode setup complete!${NC}"
    echo ""
    echo "To start the container:"
    echo "  docker-compose up -d"
    echo ""
    echo -e "${YELLOW}Note: Your Claude subscription will be used for API calls.${NC}"
}

# Setup OAuth extract mode (for remote servers)
setup_oauth_extract() {
    echo -e "${GREEN}Setting up OAuth Extract mode...${NC}"
    echo ""

    # Create directory for extracted credentials
    DOCKER_CREDS_DIR="$PROJECT_DIR/.docker-credentials"
    mkdir -p "$DOCKER_CREDS_DIR"
    chmod 700 "$DOCKER_CREDS_DIR"

    # Extract credentials
    echo -e "${YELLOW}Extracting credentials...${NC}"
    "$SCRIPT_DIR/extract-claude-credentials.sh" --output "$DOCKER_CREDS_DIR/credentials.json"

    # Create docker-compose override for extracted credentials
    cat > "$PROJECT_DIR/docker-compose.override.yml" << EOF
# OAuth extract mode - uses extracted credentials
# Generated by setup-docker-auth.sh

services:
  auto-agent-harness:
    volumes:
      - autocoder-data:/app/data
      - \${WORKSPACE_DIR:-./workspace}:/workspace
      # Mount extracted credentials
      - ./.docker-credentials:/home/autocoder/.claude:ro
EOF

    echo -e "${GREEN}Created docker-compose.override.yml with extracted credentials${NC}"

    # Generate JWT secret
    if [ ! -f "$PROJECT_DIR/.env" ] || ! grep -q "JWT_SECRET_KEY" "$PROJECT_DIR/.env" 2>/dev/null; then
        JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
        echo "JWT_SECRET_KEY=$JWT_SECRET" >> "$PROJECT_DIR/.env"
    fi

    # Add .docker-credentials to .gitignore
    if ! grep -q ".docker-credentials" "$PROJECT_DIR/.gitignore" 2>/dev/null; then
        echo ".docker-credentials/" >> "$PROJECT_DIR/.gitignore"
        echo -e "${GREEN}Added .docker-credentials to .gitignore${NC}"
    fi

    echo ""
    echo -e "${GREEN}OAuth Extract mode setup complete!${NC}"
    echo ""
    echo "Credentials extracted to: $DOCKER_CREDS_DIR/"
    echo ""
    echo "To deploy to a remote server:"
    echo "  1. Copy the entire project directory to the server"
    echo "  2. Run: docker-compose up -d"
    echo ""
    echo -e "${YELLOW}Note: Tokens may expire. Re-run this script to refresh.${NC}"
}

# Interactive mode
interactive_setup() {
    print_header
    print_mode_info

    echo -e "${CYAN}Select authentication mode:${NC}"
    echo "  1) API Key (pay-per-use)"
    echo "  2) OAuth Mount (local Docker)"
    echo "  3) OAuth Extract (remote server)"
    echo ""
    read -p "Enter choice [1-3]: " choice

    case $choice in
        1)
            setup_api_key
            ;;
        2)
            setup_oauth_mount
            ;;
        3)
            setup_oauth_extract
            ;;
        *)
            echo -e "${RED}Invalid choice${NC}"
            exit 1
            ;;
    esac
}

# Main
case "${1:-}" in
    --api-key)
        setup_api_key
        ;;
    --oauth-mount)
        setup_oauth_mount
        ;;
    --oauth-extract)
        setup_oauth_extract
        ;;
    --interactive|-i|"")
        interactive_setup
        ;;
    --help|-h)
        print_header
        print_mode_info
        echo "Usage: $0 [OPTIONS]"
        echo ""
        echo "Options:"
        echo "  --api-key        Setup API key authentication"
        echo "  --oauth-mount    Setup OAuth with volume mount"
        echo "  --oauth-extract  Extract OAuth credentials for remote server"
        echo "  --interactive    Interactive setup wizard (default)"
        echo "  --help           Show this help message"
        ;;
    *)
        echo -e "${RED}Unknown option: $1${NC}"
        echo "Run '$0 --help' for usage information."
        exit 1
        ;;
esac
